apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: taskflow
  labels:
    app: taskflow
    component: db
spec:
  containers:
    - name: postgres
      image: postgres:18
      env:
        - name: POSTGRES_DB
          value: taskflow
        - name: POSTGRES_USER
          value: taskflow
        - name: POSTGRES_PASSWORD
          # Mot de passe fictif réservé au TP.
          value: taskflow-lab-only
      ports:
        - containerPort: 5432
